trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
  drafts: false

# The agent pool the build will run on
pool:
  name: VSEngSS-MicroBuild2019
  demands: 
  - msbuild
  - VisualStudio_16.0

variables:
  - name: SolutionFile
    value: ThemeConverter/ThemeConverter.sln
  - name: Platform
    value: Any CPU
  - name: BuildConfiguration
    value: Release
    
jobs:
- job: BuildingProduct
  displayName: Building product

  steps:

  # Check out code clean from source control
  - checkout: self
    clean: true

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: $(SolutionFile)
    
  # Build the product
  - task: MSBuild@1
    displayName: 'Build product'
    inputs:
      solution: $(SolutionFile)
      platform: $(Platform)
      configuration: $(BuildConfiguration)
    continueOnError: false    
